modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/Encounter/issues/"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://github.com/Nova-Committee/Encounter"
authors = "${mod_authors}" #optional
displayTest = "IGNORE_SERVER_VERSION"
description = '''${mod_description}'''
